sudo: required
services:
  - docker


script:
  - docker build -t yanyichi/node .
  - docker images yanyichi/node

before_deploy:
  - docker login -u yanyichi  -p yycwlm143

deploy:
  provider: script
  script: docker push yanyichi/node
  on:
    branch: master